### PR TITLE
Added optional argument for the output file

### PR DESCRIPTION
**Pull request by akozlik**
Added an optional parameter to control the output file.

### CODE REVIEW

**Comment by akozlik** [comment]
Hi just wanted to follow up with this and see if you're accepting pull requests.

**Comment by matthewearl** [comment]
Sorry for the delay: I've been away from my computer for the last 10 days or so. I like the idea of having an optional output argument, however I think it'd be better with an explicit flag (-o), and argparse. Simply reading sys.argv[3] seems risky in that the user is liable to accidentally put an input file as the third argument, thereby overwriting it.

**Comment by akozlik** [comment]
No problem at all, I appreciate the reply. Argparse makes a lot of sense. I haven't done too much python work so I wasn't aware of a best practice. I'll update the codebase and issue another PR if that's OK with you.

**Comment by matthewearl** [comment]
No problem!

**Pull request closed without merging**
